jwt:
  refresh-expiration: 60000


quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:32500/template
    username: postgres
    password: 1234
  default-locale: en-US
#  flyway:
#    migrate-at-start: true
#    schemas: template
#    locations: classpath:db/migration/common,classpath:db/migration/others
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    log:
      bind-parameters: true
      sql: true
      format-sql: true
  http:
    port: 8080
    root-path: /api
  locales: en-US,pt-BR
  log:
    min-level: TRACE
    level: INFO
    category:
      org.hibernate.type.descriptor.sql.BasicBinder:
        level: TRACE
#      io.quarkus.smallrye.jwt:
#        level: DEBUG
#      io.smallrye.jwt:
#        level: DEBUG
    console:
      color: true
#      format: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %-5p[%c{1.}[%F]] (%t) %s%n%e"
      format: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %-5p[%C] (%t) %s%n%e"
  resteasy:
    gzip:
      enabled: true
      max-input: 3M
#  smallrye-jwt:
#    enabled: false


smallrye:
  jwt:
    sign:
      key:
        location: classpath:keys/privateKey.pem
    new-token:
      lifespan: 6000
    token:
      header: Authorization
      schemes: Bearer
    verify:
      algorithm: RS256
      key-format: PEM_KEY
    time-to-live: 6000
    expiration.grace: 0

mp:
  jwt:
    verify:
      publickey:
        location: classpath:keys/publicKey.pem
