jwt:
  refresh-expiration: 90000

mp:
  jwt:
    verify:
      publickey:
        location: classpath:keys/publicKey.pem
  openapi:
    model.reader: dev.sandrocaseiro.template.configs.SwaggerConfig
    filter: dev.sandrocaseiro.template.configs.SwaggerConfig

quarkus:
  datasource:
    db-kind: postgresql
  default-locale: en-US
#  flyway:
#    migrate-at-start: true
#    schemas: template
#    locations: classpath:db/migration/common,classpath:db/migration/others
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  http:
    auth:
      proactive: false
    port: 8080
  locales: en-US,pt-BR
  log:
    min-level: INFO
    level: INFO
    console:
      color: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
  resteasy:
    gzip:
      enabled: true
      max-input: 3M

smallrye:
  jwt:
    sign:
      key:
        location: classpath:keys/privateKey.pem
    new-token:
      lifespan: 6000
    token:
      header: Authorization
      schemes: Bearer
    verify:
      algorithm: RS256
      key-format: PEM_KEY
    time-to-live: 6000
    expiration.grace: 0

"%dev":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:32500/template
      username: postgres
      password: 1234
    hibernate-orm:
      log:
        bind-parameters: true
        sql: true
        format-sql: true
    http:
      root-path: /api
    log:
      min-level: TRACE
      level: INFO
      category:
        org.hibernate.type.descriptor.sql.BasicBinder:
          level: TRACE
        io.quarkus.smallrye.jwt:
          level: INFO
        io.smallrye.jwt:
          level: INFO
      console:
        format: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %-5p[%C] (%t) %s%n%e"

"%local":
  quarkus:
    config:
      profile:
        parent: dev
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:32500/template
      username: postgres
      password: 1234
    hibernate-orm:
      log:
        bind-parameters: true
    http:
      root-path: /api
    log:
      min-level: TRACE
