--CREATE TABLE public."role" (
--	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
--	"name" varchar(50) NOT NULL,
--	creation_date timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--	update_date timestamp(0) NULL,
--	active bool NOT NULL DEFAULT true,
--	CONSTRAINT role_pk PRIMARY KEY (id)
--);

--CREATE TABLE public."group" (
--	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
--	"name" varchar(50) NOT NULL,
--	creation_date timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--	update_date timestamp(0) NULL,
--	active bool NOT NULL DEFAULT true,
--	CONSTRAINT group_pk PRIMARY KEY (id)
--);

--CREATE TABLE public."user" (
--	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
--	"name" varchar(50) NOT NULL,
--	cpf varchar(11) NOT NULL,
--	email varchar(150) NOT NULL,
--	"password" varchar(150) NOT NULL,
--	group_id int4 NOT NULL,
--	balance numeric(19,4) NULL,
--	creation_date timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--	update_date timestamp(0) NULL,
--	active bool NOT NULL DEFAULT true,
--	CONSTRAINT user_email_un UNIQUE (email),
--	CONSTRAINT user_pk PRIMARY KEY (id)
--);

--CREATE TABLE public.user_role (
--	user_id int4 NOT NULL,
--	role_id int4 NOT NULL,
--	CONSTRAINT user_role_pk PRIMARY KEY (user_id, role_id)
--);
--ALTER TABLE public.user_role ADD CONSTRAINT user_role_role_fk FOREIGN KEY (role_id) REFERENCES public."role"(id);
--ALTER TABLE public.user_role ADD CONSTRAINT user_role_user_fk FOREIGN KEY (user_id) REFERENCES public."user"(id);


--insert into role (name) values ('Role 1');
--insert into role (name) values ('Role 2');
--insert into role (name) values ('Role 3');
--insert into role (name) values ('Role 4');
--
--insert into group (name) values ('Group 1');
--insert into group (name) values ('Group 2');
--insert into group (name) values ('Group 3');
--insert into group (name) values ('Group 4');
